### ISSUE TITLE
Log out to standard Logger

### ISSUE THREAD

**Issue by xqwzts** [storebrand/scheduledtask#7]
A common pattern I end up using is to duplicate the messages I want to log to both the Logger and the TaskRepository:

```
String message = "doing something worth logging";
log.info(message);
context.log(message);
```

It would be nice to instead be able set a flag to send that output to both with a single call.

Not sure if this should be per task or global.

Possibly it would be enough to flip the log level on this line:

https://github.com/storebrand/scheduledtask/blob/main/scheduledtask-db-sql/src/main/java/com/storebrand/scheduledtask/db/sql/ScheduledTaskSqlRepository.java#L461

**Comment by DagBertelsen** [comment]
Will be fixed in #17
