### ISSUE TITLE
Disable execute button when task is not active

### ISSUE THREAD

**Issue by xqwzts** [storebrand/scheduledtask#8]
The execute button is rendered [here](https://github.com/storebrand/scheduledtask/blob/main/scheduledtask-localinspect/src/main/java/com/storebrand/scheduledtask/localinspect/LocalHtmlInspectScheduler.java#L378):

```
                + "        <button class=\"btn btn-primary\" type=\"submit\">Execute Scheduler</button>"
```

We could set the disabled property based on the isActive() state since it would not execute an inactive task anyway:
```
                + "        <button class=\"btn btn-primary\" type=\"submit\"" + !schedule.isActive() ? "disabled" : "" + ">Execute Scheduler</button>"
```

**Comment by DagBertelsen** [comment]
This will be fixed in #17
